package com.targettrust.petshop.swing;

import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menubar = new javax.swing.JMenuBar();
        mAgendamento = new javax.swing.JMenu();
        miManutencaoAg = new javax.swing.JMenuItem();
        mCliente = new javax.swing.JMenu();
        miManutencaoCli = new javax.swing.JMenuItem();
        mAjuda = new javax.swing.JMenu();
        miDocumentacao = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PetShop4j - v3");

        mAgendamento.setText("Agendamento");

        miManutencaoAg.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        miManutencaoAg.setText("Manutenção");
        miManutencaoAg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miManutencaoAgActionPerformed(evt);
            }
        });
        mAgendamento.add(miManutencaoAg);

        menubar.add(mAgendamento);

        mCliente.setText("Cliente");

        miManutencaoCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        miManutencaoCli.setText("Manutenção");
        miManutencaoCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miManutencaoCliActionPerformed(evt);
            }
        });
        mCliente.add(miManutencaoCli);

        menubar.add(mCliente);

        mAjuda.setText("Ajuda");

        miDocumentacao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        miDocumentacao.setText("Documentação");
        miDocumentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDocumentacaoActionPerformed(evt);
            }
        });
        mAjuda.add(miDocumentacao);
        mAjuda.add(jSeparator1);

        miSobre.setText("Sobre");
        miSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSobreActionPerformed(evt);
            }
        });
        mAjuda.add(miSobre);

        menubar.add(mAjuda);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSobreActionPerformed
        JOptionPane.showMessageDialog(this, "Copyright(c) TargetTrust\nTreinamento de Java Fundamentos da Linguagem");
    }//GEN-LAST:event_miSobreActionPerformed

    private void miDocumentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDocumentacaoActionPerformed
        nenhumaAcao();
    }//GEN-LAST:event_miDocumentacaoActionPerformed

    private void miManutencaoCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miManutencaoCliActionPerformed
        ManutencaoCliente mc = new ManutencaoCliente();
        desktopPane.add(mc);
        mc.setVisible(true);
    }//GEN-LAST:event_miManutencaoCliActionPerformed

    private void miManutencaoAgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miManutencaoAgActionPerformed
        ManutencaoAgenda ma = new ManutencaoAgenda(this);
        desktopPane.add(ma);
        ma.setVisible(true);
    }//GEN-LAST:event_miManutencaoAgActionPerformed

    private void nenhumaAcao() {
        JOptionPane.showMessageDialog(this, "Ooops! Nenhuma ação implementada.");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mAgendamento;
    private javax.swing.JMenu mAjuda;
    private javax.swing.JMenu mCliente;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JMenuItem miDocumentacao;
    private javax.swing.JMenuItem miManutencaoAg;
    private javax.swing.JMenuItem miManutencaoCli;
    private javax.swing.JMenuItem miSobre;
    // End of variables declaration//GEN-END:variables
}
